# .github/workflows/docker-build.yml
name: Build and Push Python Docker Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64,amd64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Git SHA
        run: echo "SHA_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ env.SHA_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: Adybaeva/dev-code
          token: ${{ secrets.GH_PAT }}
          path: gitops-code

      - name: Update image tag in values file
        run: |
          cd gitops-code
          yq eval '.image.tag = "${{ env.SHA_TAG }}"' -i values-dev.yaml

      - name: Commit and push changes
        run: |
          cd gitops-code
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values-dev.yaml
          git commit -m "Update image tag to ${{ env.SHA_TAG }}"
          git push
